/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rocnikovyprojekt1.e;

import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author 55fil
 */
public class Ruleta1E_JFrame extends javax.swing.JFrame {

    private double tokeny = 500;
    private double Zisk = 0;
    private double Ziskbarva = 0;
    private double ZiskCislo = 0;
    private double ZiskSkupinaCisel = 0;
    private double Ziskpo = 0;
    private int pocetToceni = 0;
    private int potvrdCislo = 0;
    private int NahodneCislo = 0;
    private int dobaToceni = 90;

    /**
     * Creates new form Ruleta_JFrame
     */
    public Ruleta1E_JFrame() {
        initComponents();
        PocetTokenVyojLabel1.setText(String.valueOf(tokeny));
        ZiskCislojLabel.setText(String.valueOf(Zisk));
        PocetTocenijLabel.setText(String.valueOf(pocetToceni));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ZnovujDialog = new javax.swing.JDialog();
        AnojButton = new javax.swing.JButton();
        NejButton = new javax.swing.JButton();
        DialogHratZnovujLabel = new javax.swing.JLabel();
        JakHratjFrame = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ZpetJakHratjButton = new javax.swing.JButton();
        OpravdujDialog = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        AnojButton2 = new javax.swing.JButton();
        NejButton2 = new javax.swing.JButton();
        UkoncitjDialog = new javax.swing.JDialog();
        UkoncitHrujLabel = new javax.swing.JLabel();
        AnojButton3 = new javax.swing.JButton();
        NejButton3 = new javax.swing.JButton();
        PocetTokenjLabel = new javax.swing.JLabel();
        PocetTokenVyojLabel1 = new javax.swing.JLabel();
        SazkajLabel = new javax.swing.JLabel();
        SazkajComboBox = new javax.swing.JComboBox<>();
        KolikSazkajLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        KolikSazkaCislojLabel = new javax.swing.JLabel();
        SazkajSpinner1 = new javax.swing.JSpinner();
        SazkaCislojButton = new javax.swing.JButton();
        RoztocitKolojButton = new javax.swing.JButton();
        PoRoztocenijPanel = new javax.swing.JPanel();
        LosovanijLabel = new javax.swing.JLabel();
        ZiskStratajLabel = new javax.swing.JLabel();
        ZiskCislojLabel = new javax.swing.JLabel();
        VylosovaneCislojLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PocetTocenijLabel = new javax.swing.JLabel();
        TextJedenZiskjLabel = new javax.swing.JLabel();
        JedenZiskjLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BarvajLabel = new javax.swing.JLabel();
        BarvajComboBox = new javax.swing.JComboBox<>();
        KolikBarvaCastPrvnijLabel = new javax.swing.JLabel();
        KolikSazkaNaJakeBarvyjLabel = new javax.swing.JLabel();
        BarvajSpinner1 = new javax.swing.JSpinner();
        PotvrdCislojLabel = new javax.swing.JLabel();
        SkupinaCiseljLabel = new javax.swing.JLabel();
        SkupinaCiseljComboBox = new javax.swing.JComboBox<>();
        KolikSkupinaCiseljLabel = new javax.swing.JLabel();
        JakaSkupinaCiselSazkajLabel18 = new javax.swing.JLabel();
        SkupinaCiseljSpinner = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        HratZnovujButton1 = new javax.swing.JButton();
        UkoncitjButton = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        ZnovujDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        ZnovujDialog.setAlwaysOnTop(true);
        ZnovujDialog.setLocationByPlatform(true);
        ZnovujDialog.setResizable(false);

        AnojButton.setBackground(new java.awt.Color(204, 204, 204));
        AnojButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        AnojButton.setForeground(new java.awt.Color(0, 0, 0));
        AnojButton.setText("Ano");
        AnojButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AnojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnojButtonActionPerformed(evt);
            }
        });

        NejButton.setBackground(new java.awt.Color(204, 204, 204));
        NejButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        NejButton.setForeground(new java.awt.Color(0, 0, 0));
        NejButton.setText("Ne");
        NejButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NejButtonActionPerformed(evt);
            }
        });

        DialogHratZnovujLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DialogHratZnovujLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DialogHratZnovujLabel.setText("Chcete hrát znovu?");

        javax.swing.GroupLayout ZnovujDialogLayout = new javax.swing.GroupLayout(ZnovujDialog.getContentPane());
        ZnovujDialog.getContentPane().setLayout(ZnovujDialogLayout);
        ZnovujDialogLayout.setHorizontalGroup(
            ZnovujDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZnovujDialogLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(AnojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZnovujDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DialogHratZnovujLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ZnovujDialogLayout.setVerticalGroup(
            ZnovujDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZnovujDialogLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(DialogHratZnovujLabel)
                .addGap(46, 46, 46)
                .addGroup(ZnovujDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NejButton)
                    .addComponent(AnojButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        JakHratjFrame.setAlwaysOnTop(true);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText(" 3) Klikněte na tlačítko potvrďit. Tím se Vám vypíšou vaše sázky o kousek níže.");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setText("Sázíte na jednu ze skupin a padne číslo z Vaší skupiny, vyhráváte 2x sázku.");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("      zadejte jako sázku tokenů 0.");

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setText(" 3) Vsazením na skupinu čísel jde vyhrát:");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setText(" 4) Vsazením na cokoliv jde prohrát:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText(" 4) Vyberte hodnutu Vaší sázky na danou možnost sázení.");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText(" 5) Roztočte ruletu, kliknutím na tlačítko \"Roztočit ruletu\".");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Možnosti výhry:");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText(" 2) Vsazením na barvu jde vyhrát:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Sázíte na jednu z barev a padne vaše barva, vyhráváte 2x sázku.");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setText("Sázíte na jakékoliv jiné číslo a padne Vámi vybrané číslo, vyhráváte 3x sázku.");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Jak hrát:");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setText(" 1) Vsazením na číslo jde vyhrát:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText(" 1) Každý hráč má na začátku hry 500 tokenů.");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel16.setText("Sázíte na 0, padne 0 vyhráváte 10x sázku.");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setText(" 2) Vyberte číslo, které chcete vsadit. Pokud nechcete vsadit na jednu z možností,");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setText("Sázíte na cokoliv a nevyhrajete, odebere se Vám celá sázka.");

        ZpetJakHratjButton.setBackground(new java.awt.Color(204, 204, 204));
        ZpetJakHratjButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ZpetJakHratjButton.setForeground(new java.awt.Color(0, 0, 0));
        ZpetJakHratjButton.setText("Zpět");
        ZpetJakHratjButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ZpetJakHratjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ZpetJakHratjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZpetJakHratjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JakHratjFrameLayout = new javax.swing.GroupLayout(JakHratjFrame.getContentPane());
        JakHratjFrame.getContentPane().setLayout(JakHratjFrameLayout);
        JakHratjFrameLayout.setHorizontalGroup(
            JakHratjFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JakHratjFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(101, 101, 101))
            .addGroup(JakHratjFrameLayout.createSequentialGroup()
                .addGroup(JakHratjFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JakHratjFrameLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ZpetJakHratjButton))
                    .addGroup(JakHratjFrameLayout.createSequentialGroup()
                        .addGroup(JakHratjFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JakHratjFrameLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(JakHratjFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)))
                            .addGroup(JakHratjFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(JakHratjFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel15)))
                            .addGroup(JakHratjFrameLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel18))
                            .addGroup(JakHratjFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel19))
                            .addGroup(JakHratjFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JakHratjFrameLayout.setVerticalGroup(
            JakHratjFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JakHratjFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JakHratjFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JakHratjFrameLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JakHratjFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ZpetJakHratjButton)))
                .addContainerGap())
        );

        OpravdujDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        OpravdujDialog.setAlwaysOnTop(true);
        OpravdujDialog.setLocation(new java.awt.Point(0, 0));
        OpravdujDialog.setLocationByPlatform(true);
        OpravdujDialog.setResizable(false);

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Opravdu chcete hrát znovu?");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        AnojButton2.setBackground(new java.awt.Color(204, 204, 204));
        AnojButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AnojButton2.setForeground(new java.awt.Color(0, 0, 0));
        AnojButton2.setText("Ano");
        AnojButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AnojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnojButton2ActionPerformed(evt);
            }
        });

        NejButton2.setBackground(new java.awt.Color(204, 204, 204));
        NejButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        NejButton2.setForeground(new java.awt.Color(0, 0, 0));
        NejButton2.setText("Ne");
        NejButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NejButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OpravdujDialogLayout = new javax.swing.GroupLayout(OpravdujDialog.getContentPane());
        OpravdujDialog.getContentPane().setLayout(OpravdujDialogLayout);
        OpravdujDialogLayout.setHorizontalGroup(
            OpravdujDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpravdujDialogLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(AnojButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(NejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OpravdujDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        OpravdujDialogLayout.setVerticalGroup(
            OpravdujDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpravdujDialogLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(OpravdujDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NejButton2)
                    .addComponent(AnojButton2))
                .addGap(41, 41, 41))
        );

        UkoncitjDialog.setAlwaysOnTop(true);
        UkoncitjDialog.setLocationByPlatform(true);

        UkoncitHrujLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        UkoncitHrujLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UkoncitHrujLabel.setText("Opravdu chcete ukončit hru?");
        UkoncitHrujLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        AnojButton3.setBackground(new java.awt.Color(204, 204, 204));
        AnojButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AnojButton3.setForeground(new java.awt.Color(0, 0, 0));
        AnojButton3.setText("Ano");
        AnojButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AnojButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnojButton3ActionPerformed(evt);
            }
        });

        NejButton3.setBackground(new java.awt.Color(204, 204, 204));
        NejButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        NejButton3.setForeground(new java.awt.Color(0, 0, 0));
        NejButton3.setText("Ne");
        NejButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NejButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UkoncitjDialogLayout = new javax.swing.GroupLayout(UkoncitjDialog.getContentPane());
        UkoncitjDialog.getContentPane().setLayout(UkoncitjDialogLayout);
        UkoncitjDialogLayout.setHorizontalGroup(
            UkoncitjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UkoncitjDialogLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(AnojButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NejButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UkoncitjDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UkoncitHrujLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
        UkoncitjDialogLayout.setVerticalGroup(
            UkoncitjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UkoncitjDialogLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(UkoncitHrujLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(UkoncitjDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnojButton3)
                    .addComponent(NejButton3))
                .addGap(33, 33, 33))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ruleta");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        PocetTokenjLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PocetTokenjLabel.setText("Aktuální počet tokenů:");

        PocetTokenVyojLabel1.setBackground(new java.awt.Color(204, 204, 204));
        PocetTokenVyojLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PocetTokenVyojLabel1.setForeground(new java.awt.Color(0, 0, 0));

        SazkajLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SazkajLabel.setText("Na jaké číslo sázíte:");

        SazkajComboBox.setBackground(new java.awt.Color(204, 204, 204));
        SazkajComboBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SazkajComboBox.setForeground(new java.awt.Color(0, 0, 0));
        SazkajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36" }));
        SazkajComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        KolikSazkajLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        KolikSazkajLabel.setText("Kolik vsadíte na číslo");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        KolikSazkaCislojLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        KolikSazkaCislojLabel.setText(" ");

        SazkajSpinner1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SazkajSpinner1.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, null, 1.0d));
        SazkajSpinner1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SazkaCislojButton.setBackground(new java.awt.Color(204, 204, 204));
        SazkaCislojButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SazkaCislojButton.setForeground(new java.awt.Color(0, 0, 0));
        SazkaCislojButton.setText("Potvrdit");
        SazkaCislojButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SazkaCislojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SazkaCislojButtonActionPerformed(evt);
            }
        });

        RoztocitKolojButton.setBackground(new java.awt.Color(204, 204, 204));
        RoztocitKolojButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        RoztocitKolojButton.setForeground(new java.awt.Color(0, 0, 0));
        RoztocitKolojButton.setText("Roztočit ruletu");
        RoztocitKolojButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RoztocitKolojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoztocitKolojButtonActionPerformed(evt);
            }
        });

        PoRoztocenijPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LosovanijLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LosovanijLabel.setText("Vylosované číslo je:");

        ZiskStratajLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ZiskStratajLabel.setText("Celkový/á zisk/stráta:");

        ZiskCislojLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ZiskCislojLabel.setText(" ");

        VylosovaneCislojLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        VylosovaneCislojLabel.setText(" ");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setText("Počet točení:");

        PocetTocenijLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PocetTocenijLabel.setText(" ");

        TextJedenZiskjLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TextJedenZiskjLabel.setText("Zisk/Stráta:");

        JedenZiskjLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        JedenZiskjLabel.setText(" ");

        javax.swing.GroupLayout PoRoztocenijPanelLayout = new javax.swing.GroupLayout(PoRoztocenijPanel);
        PoRoztocenijPanel.setLayout(PoRoztocenijPanelLayout);
        PoRoztocenijPanelLayout.setHorizontalGroup(
            PoRoztocenijPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoRoztocenijPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PoRoztocenijPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PoRoztocenijPanelLayout.createSequentialGroup()
                        .addComponent(LosovanijLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VylosovaneCislojLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PoRoztocenijPanelLayout.createSequentialGroup()
                        .addComponent(TextJedenZiskjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JedenZiskjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PoRoztocenijPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PocetTocenijLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PoRoztocenijPanelLayout.createSequentialGroup()
                        .addComponent(ZiskStratajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZiskCislojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PoRoztocenijPanelLayout.setVerticalGroup(
            PoRoztocenijPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PoRoztocenijPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PoRoztocenijPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LosovanijLabel)
                    .addComponent(VylosovaneCislojLabel))
                .addGap(18, 18, 18)
                .addGroup(PoRoztocenijPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextJedenZiskjLabel)
                    .addComponent(JedenZiskjLabel))
                .addGap(18, 18, 18)
                .addGroup(PoRoztocenijPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(PocetTocenijLabel))
                .addGap(18, 18, 18)
                .addGroup(PoRoztocenijPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZiskStratajLabel)
                    .addComponent(ZiskCislojLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/casino-roulette02.jpg"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(556, 512));

        BarvajLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BarvajLabel.setText("Sázíte na barvu:");

        BarvajComboBox.setBackground(new java.awt.Color(204, 204, 204));
        BarvajComboBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BarvajComboBox.setForeground(new java.awt.Color(0, 0, 0));
        BarvajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Červená", "Černá" }));
        BarvajComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        KolikBarvaCastPrvnijLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        KolikBarvaCastPrvnijLabel.setText("Kolik sázíte na ");

        KolikSazkaNaJakeBarvyjLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        KolikSazkaNaJakeBarvyjLabel.setText(" ");

        BarvajSpinner1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BarvajSpinner1.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, null, 1.0d));
        BarvajSpinner1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PotvrdCislojLabel.setBackground(new java.awt.Color(204, 204, 204));
        PotvrdCislojLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PotvrdCislojLabel.setForeground(new java.awt.Color(0, 0, 0));
        PotvrdCislojLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PotvrdCislojLabel.setText(" ");
        PotvrdCislojLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PotvrdCislojLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SkupinaCiseljLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SkupinaCiseljLabel.setText("Sázíte na skupinu čísel:");

        SkupinaCiseljComboBox.setBackground(new java.awt.Color(204, 204, 204));
        SkupinaCiseljComboBox.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SkupinaCiseljComboBox.setForeground(new java.awt.Color(0, 0, 0));
        SkupinaCiseljComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1-12", "13-24", "25-36" }));
        SkupinaCiseljComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        KolikSkupinaCiseljLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        KolikSkupinaCiseljLabel.setText("Kolik sázíte na skupinu čísel");

        JakaSkupinaCiselSazkajLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        JakaSkupinaCiselSazkajLabel18.setText(" ");

        SkupinaCiseljSpinner.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SkupinaCiseljSpinner.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, null, 1.0d));
        SkupinaCiseljSpinner.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setPreferredSize(new java.awt.Dimension(556, 34));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Pravidla");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        HratZnovujButton1.setBackground(new java.awt.Color(204, 204, 204));
        HratZnovujButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        HratZnovujButton1.setForeground(new java.awt.Color(0, 0, 0));
        HratZnovujButton1.setText("Hrát znovu");
        HratZnovujButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HratZnovujButton1.setPreferredSize(new java.awt.Dimension(90, 30));
        HratZnovujButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HratZnovujButton1ActionPerformed(evt);
            }
        });

        UkoncitjButton.setBackground(new java.awt.Color(204, 204, 204));
        UkoncitjButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        UkoncitjButton.setForeground(new java.awt.Color(0, 0, 0));
        UkoncitjButton.setText("Ukončit");
        UkoncitjButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UkoncitjButton.setPreferredSize(new java.awt.Dimension(90, 30));
        UkoncitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UkoncitjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(HratZnovujButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(UkoncitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HratZnovujButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UkoncitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("https://dribbble.com/shots/4218363-Casino-Roulette");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PoRoztocenijPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PocetTokenjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PocetTokenVyojLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PotvrdCislojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(382, 382, 382)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(SazkajLabel)
                                            .addGap(67, 67, 67)
                                            .addComponent(SazkajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(BarvajLabel)
                                            .addGap(48, 48, 48)
                                            .addComponent(BarvajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SazkaCislojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(SkupinaCiseljLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SkupinaCiseljComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(KolikSazkajLabel)
                                                        .addComponent(KolikBarvaCastPrvnijLabel))
                                                    .addGap(70, 70, 70))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(KolikSkupinaCiseljLabel)
                                                    .addGap(5, 5, 5)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(JakaSkupinaCiselSazkajLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(KolikSazkaNaJakeBarvyjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(KolikSazkaCislojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BarvajSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SazkajSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SkupinaCiseljSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(RoztocitKolojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PocetTokenjLabel)
                            .addComponent(PocetTokenVyojLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SazkajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SazkajLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BarvajLabel)
                            .addComponent(BarvajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SazkaCislojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SkupinaCiseljLabel)
                            .addComponent(SkupinaCiseljComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(KolikSazkajLabel)
                                .addComponent(KolikSazkaCislojLabel)
                                .addComponent(SazkajSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(KolikSazkaNaJakeBarvyjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BarvajSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(KolikBarvaCastPrvnijLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KolikSkupinaCiseljLabel)
                            .addComponent(JakaSkupinaCiselSazkajLabel18)
                            .addComponent(SkupinaCiseljSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RoztocitKolojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(PotvrdCislojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PoRoztocenijPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SazkaCislojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SazkaCislojButtonActionPerformed
        //Potrvzovací tlačítko
        String CisloSazky = String.valueOf(SazkajComboBox.getSelectedItem());
        String barva = String.valueOf(BarvajComboBox.getSelectedItem());
        String skupinaCisel = String.valueOf(SkupinaCiseljComboBox.getSelectedItem());
        potvrdCislo = Integer.parseInt(CisloSazky);
        KolikSazkaCislojLabel.setText(String.valueOf(potvrdCislo));
        PotvrdCislojLabel.setText(String.valueOf(" "));
        KolikSazkaNaJakeBarvyjLabel.setText(barva);
        JakaSkupinaCiselSazkajLabel18.setText(skupinaCisel);
    }//GEN-LAST:event_SazkaCislojButtonActionPerformed

    private void RoztocitKolojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoztocitKolojButtonActionPerformed
        //tlačítko na roztočení rulety

        String barva = String.valueOf(BarvajComboBox.getSelectedItem());
        String CisloSazky = String.valueOf(SazkajComboBox.getSelectedItem());
        String skupinaCisel = String.valueOf(SkupinaCiseljComboBox.getSelectedItem());
        double SazkaTokenCislo = (double) SazkajSpinner1.getValue();
        double SazkaTokenBarva = (double) BarvajSpinner1.getValue();
        double SazkaTokenSkupinaCsiel = (double) SkupinaCiseljSpinner.getValue();
        NahodneCislo = (int) (Math.floor(Math.random() * 37));
        PotvrdCislojLabel.setText(String.valueOf(" "));
        int CslSa = Integer.parseInt(CisloSazky);
        // náhodné číslo
        if (CslSa != potvrdCislo /* Nejdřív potvrď pak hraj*/ || (SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) > tokeny /*Pro moc velkou sázku*/ || barva != KolikSazkaNaJakeBarvyjLabel.getText() || skupinaCisel != JakaSkupinaCiselSazkajLabel18.getText() || (SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) == 0) {
            if (CslSa != potvrdCislo) {
                PotvrdCislojLabel.setText(String.valueOf("Nejdříve potvrdťe číslo"));
            } else if ((SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) > tokeny) {
                PotvrdCislojLabel.setText(String.valueOf("Sázíte moc velké číslo"));
            } else if (barva != String.valueOf(SazkajComboBox.getSelectedItem())) {
                PotvrdCislojLabel.setText(String.valueOf("Nejdříve potvrdťe barvu"));
            } else if (skupinaCisel != JakaSkupinaCiselSazkajLabel18.getText()) {
                PotvrdCislojLabel.setText(String.valueOf("Nejdříve potvrdťe skupinu čísel"));
            } else if ((SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) == 0) {
                PotvrdCislojLabel.setText(String.valueOf("Sázíte na vše 0"));
            } else {
                PotvrdCislojLabel.setText(String.valueOf("Musíte vybrat na co sázíte"));
            }
        } else {
            TimerTask task = new TimerTask() {
                public void run() {
                    try {
                        RoztocitKolojButton.setEnabled(false);
                        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/casino-roulette.gif")));
                        TimeUnit.SECONDS.sleep(3);
                    } catch (InterruptedException ex) {
                        System.out.println("Chyba animace rulety");
                    }
                    jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/casino-roulette02.jpg")));
                    RoztocitKolojButton.setEnabled(true);
                    VylosovaneCislojLabel.setText(String.valueOf(NahodneCislo));
                    if (tokeny > 0 && CslSa == potvrdCislo && 
                            (SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) <= tokeny && 
                            barva == KolikSazkaNaJakeBarvyjLabel.getText() && 
                            skupinaCisel == JakaSkupinaCiselSazkajLabel18.getText() && 
                            (SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) != 0) {
                        // vypisování prohry nebo výhry
                        Zisk = Ziskbarva + ZiskCislo + ZiskSkupinaCisel;
                        Ziskpo = Zisk + Ziskpo;
                        tokeny = tokeny + Zisk;
                        JedenZiskjLabel.setText(String.valueOf(Zisk));
                        ZiskCislojLabel.setText(String.valueOf(Ziskpo));
                        PocetTokenVyojLabel1.setText(String.valueOf(tokeny));

                        // Kolikrát jste už točili
                        pocetToceni++;
                        PocetTocenijLabel.setText(String.valueOf(pocetToceni));
                    }

                    if (tokeny <= 0/*málo tokenů skončila hra */) {
                        PocetTokenVyojLabel1.setText(String.valueOf("Došly tokeny"));
                        RoztocitKolojButton.setEnabled(false);
                        ZnovujDialog.setSize(372, 210);
                        ZnovujDialog.setVisible(true);

                    }
                }
            };
            dobaToceni = (int) (Math.floor((Math.random() * 100) + dobaToceni));
            Timer timer = new Timer();
            long delay = dobaToceni;
            timer.schedule(task, delay);

            if (NahodneCislo == CslSa) {
                if (NahodneCislo == 0 && CslSa == 0) {  // Když vsadíte na 0 a padla 0
                    ZiskCislo = (SazkaTokenCislo * 10) - SazkaTokenCislo;
                } else {                                // Když vsadíte jakékoliv jiné číslo a padne vám stejné číslo 
                    ZiskCislo = SazkaTokenCislo * 2;
                }

            } else { // Když prohrajete
                ZiskCislo = SazkaTokenCislo * -1;
            }

        }
        if (barva != KolikSazkaNaJakeBarvyjLabel.getText() || (SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) > tokeny /*Pro moc velkou sázku*/ || (SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) == 0) {
            if ((SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) > tokeny) {
                PotvrdCislojLabel.setText(String.valueOf("Sázíte moc velké číslo"));
            } else if ((SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) == 0) {
                PotvrdCislojLabel.setText(String.valueOf("Sázíte na vše 0"));
            } else {
                PotvrdCislojLabel.setText(String.valueOf("Nejdříve potvrdťe barvu"));
            }

        } else {
            if (barva == "Červená") {
                for (int cervena = 2; cervena <= 36; cervena++) { // pro červenou barvu (sudá čísla)
                    if (cervena % 2 == 0 && cervena == NahodneCislo && barva == "Červená") {
                        Ziskbarva = SazkaTokenBarva * 1;
                    } else if (NahodneCislo % 2 == 1 || NahodneCislo == 0) { // Když prohrajete
                        Ziskbarva = SazkaTokenBarva * -1;
                    }

                }
            } else if (barva == "Černá") {
                for (int cerna = 1; cerna <= 36; cerna++) { // pro černou barvu (lichá čísla)
                    if (cerna % 2 == 1 && cerna == NahodneCislo && barva == "Černá") {
                        Ziskbarva = SazkaTokenBarva * 1;
                    } else if (NahodneCislo % 2 == 0 || NahodneCislo == 0) { // Když prohrajete
                        Ziskbarva = SazkaTokenBarva * -1;
                    }
                }
            }

        }
        if (skupinaCisel != JakaSkupinaCiselSazkajLabel18.getText() || (SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) > tokeny /*Pro moc velkou sázku*/ || (SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) == 0) {
            if ((SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) > tokeny) {
                PotvrdCislojLabel.setText(String.valueOf("Sázíte moc velké číslo"));
            } else if ((SazkaTokenCislo + SazkaTokenBarva + SazkaTokenSkupinaCsiel) == 0) {
                PotvrdCislojLabel.setText(String.valueOf("Sázíte na vše 0"));
            } else {
                PotvrdCislojLabel.setText(String.valueOf("Nejdříve potvrdťe skupinu čísel"));
            }

        } else {
            if (skupinaCisel == "1-12") {
                for (int skupCis = 1; skupCis <= 12; skupCis++) {
                    if (skupCis == NahodneCislo && skupinaCisel == "1-12") {
                        ZiskSkupinaCisel = SazkaTokenSkupinaCsiel * 1;
                    } else if (NahodneCislo > 12 || skupinaCisel != "1-12" || NahodneCislo == 0) {
                        ZiskSkupinaCisel = SazkaTokenSkupinaCsiel * -1;
                    }
                }
            } else if (skupinaCisel == "13-24") {
                for (int skupCis = 13; skupCis <= 24; skupCis++) {
                    if (skupCis == NahodneCislo && skupinaCisel == "13-24") {
                        ZiskSkupinaCisel = SazkaTokenSkupinaCsiel * 1;
                    } else if (NahodneCislo > 24 || NahodneCislo < 13 || skupinaCisel != "13-24" || NahodneCislo == 0) {
                        ZiskSkupinaCisel = SazkaTokenSkupinaCsiel * -1;
                    }
                }
            } else if (skupinaCisel == "25-36") {
                for (int skupCis = 25; skupCis <= 36; skupCis++) {
                    if (skupCis == NahodneCislo && skupinaCisel == "25-36") {
                        ZiskSkupinaCisel = SazkaTokenSkupinaCsiel * 1;
                    } else if (NahodneCislo < 25 || skupinaCisel != "25-36" || NahodneCislo == 0) {
                        ZiskSkupinaCisel = SazkaTokenSkupinaCsiel * -1;
                    }
                }
            }

        }


    }//GEN-LAST:event_RoztocitKolojButtonActionPerformed

    private void UkoncitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UkoncitjButtonActionPerformed
        // tlačítko pro uzavření programu
        UkoncitjDialog.setSize(300, 170);
        UkoncitjDialog.setVisible(true);
    }//GEN-LAST:event_UkoncitjButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // tlačítko na otevření pravidel
        JakHratjFrame.setSize(802, 574);
        JakHratjFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AnojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnojButtonActionPerformed
        //tlačítko ano hrát znovu, když dojdou tokeny
        ZnovuHrat();
        ZnovujDialog.setVisible(false);
    }//GEN-LAST:event_AnojButtonActionPerformed
    private void NejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NejButtonActionPerformed
        //tlačítko ne nehrát znovu, zavřit aplikaci
        System.exit(0);
    }//GEN-LAST:event_NejButtonActionPerformed

    private void ZpetJakHratjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZpetJakHratjButtonActionPerformed
        // tlačítko zpět ve framu s pravidlami
        JakHratjFrame.setVisible(false);
    }//GEN-LAST:event_ZpetJakHratjButtonActionPerformed

    private void AnojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnojButton2ActionPerformed
        // tlačítko ano, poté co kliknu na tlčítko chci hrát znovu
        ZnovuHrat();
        OpravdujDialog.setVisible(false);
    }//GEN-LAST:event_AnojButton2ActionPerformed

    private void NejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NejButton2ActionPerformed
        // tlačítko ne, poté co kliknu na tlčítko chci hrát znovu
        OpravdujDialog.setVisible(false);
    }//GEN-LAST:event_NejButton2ActionPerformed

    private void HratZnovujButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HratZnovujButton1ActionPerformed
        // tlačítko na hlavním framu "hrát znovu"
        OpravdujDialog.setSize(300, 190);
        OpravdujDialog.setVisible(true);
    }//GEN-LAST:event_HratZnovujButton1ActionPerformed

    private void AnojButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnojButton3ActionPerformed
        // tlačítko ano, poté co kliknu na tlačítko "ukončit"
        System.exit(0);
    }//GEN-LAST:event_AnojButton3ActionPerformed

    private void NejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NejButton3ActionPerformed
        // tlačítko ne, poté co kliknu na tlačítko "ukončit"
        UkoncitjDialog.setVisible(false);
    }//GEN-LAST:event_NejButton3ActionPerformed

    public void ZnovuHrat() { // metoda, která vrátí program do původního stavu
        tokeny = 500;
        Zisk = 0;
        Ziskbarva = 0;
        ZiskCislo = 0;
        ZiskSkupinaCisel = 0;
        Ziskpo = 0;
        pocetToceni = 0;
        potvrdCislo = 0;
        PocetTokenVyojLabel1.setText(String.valueOf(tokeny));
        ZiskCislojLabel.setText(String.valueOf(Zisk));
        PocetTocenijLabel.setText(String.valueOf(pocetToceni));
        KolikSazkaCislojLabel.setText(String.valueOf(" "));
        KolikSazkaNaJakeBarvyjLabel.setText(" ");
        JakaSkupinaCiselSazkajLabel18.setText(" ");
        SazkajSpinner1.setValue(1.0);
        SkupinaCiseljSpinner.setValue(1.0);
        BarvajSpinner1.setValue(1.0);
        PotvrdCislojLabel.setText(" ");
        RoztocitKolojButton.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ruleta1E_JFrame().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnojButton;
    private javax.swing.JButton AnojButton2;
    private javax.swing.JButton AnojButton3;
    private javax.swing.JComboBox<String> BarvajComboBox;
    private javax.swing.JLabel BarvajLabel;
    private javax.swing.JSpinner BarvajSpinner1;
    private javax.swing.JLabel DialogHratZnovujLabel;
    private javax.swing.JButton HratZnovujButton1;
    private javax.swing.JFrame JakHratjFrame;
    private javax.swing.JLabel JakaSkupinaCiselSazkajLabel18;
    private javax.swing.JLabel JedenZiskjLabel;
    private javax.swing.JLabel KolikBarvaCastPrvnijLabel;
    private javax.swing.JLabel KolikSazkaCislojLabel;
    private javax.swing.JLabel KolikSazkaNaJakeBarvyjLabel;
    private javax.swing.JLabel KolikSazkajLabel;
    private javax.swing.JLabel KolikSkupinaCiseljLabel;
    private javax.swing.JLabel LosovanijLabel;
    private javax.swing.JButton NejButton;
    private javax.swing.JButton NejButton2;
    private javax.swing.JButton NejButton3;
    private javax.swing.JDialog OpravdujDialog;
    private javax.swing.JPanel PoRoztocenijPanel;
    private javax.swing.JLabel PocetTocenijLabel;
    private javax.swing.JLabel PocetTokenVyojLabel1;
    private javax.swing.JLabel PocetTokenjLabel;
    private javax.swing.JLabel PotvrdCislojLabel;
    private javax.swing.JButton RoztocitKolojButton;
    private javax.swing.JButton SazkaCislojButton;
    private javax.swing.JComboBox<String> SazkajComboBox;
    private javax.swing.JLabel SazkajLabel;
    private javax.swing.JSpinner SazkajSpinner1;
    private javax.swing.JComboBox<String> SkupinaCiseljComboBox;
    private javax.swing.JLabel SkupinaCiseljLabel;
    private javax.swing.JSpinner SkupinaCiseljSpinner;
    private javax.swing.JLabel TextJedenZiskjLabel;
    private javax.swing.JLabel UkoncitHrujLabel;
    private javax.swing.JButton UkoncitjButton;
    private javax.swing.JDialog UkoncitjDialog;
    private javax.swing.JLabel VylosovaneCislojLabel;
    private javax.swing.JLabel ZiskCislojLabel;
    private javax.swing.JLabel ZiskStratajLabel;
    private javax.swing.JDialog ZnovujDialog;
    private javax.swing.JButton ZpetJakHratjButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
